name: coverage

on: [pull_request]

jobs:
  coverage-foundry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: yarn coverage --report lcov
      - name: Codecov coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}